title: "Chess Openings Site"
description: "A comprehensive static website about various chess openings."
baseurl: ""
url: "https://fl448341.github.io/www01"
theme: minima
collections:
  pages:
    output: true
markdown: kramdown
permalink: pretty
