name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

  
      - name: Generate Markdown files with Python
        run: |
          python generate_site.py

      - name: Set up Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  
          bundler-cache: true

    
      - name: Install Jekyll dependencies
        run: |
          bundle install

  
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
